<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeBehind="Accounting_Tree.aspx.cs" Inherits="Elite_system.Accounting_Tree" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style>
        .Drop {
            background-color: gold;
            font-weight: 600;
            border-style: groove;
        }

        .auto-style1 {
            width: 107%;
        }

        .COLR {
            width: 50%;
        }

        @media only screen and (max-width: 1000px) {
            .COLR {
                width: 50%;
                display: contents;
            }
        }

        .Grid {
            width: 100%;
            text-align: center;
            direction: rtl;
        }
    </style>


    <link href="Content/css/select2.min.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
            <section class="text-center" style="padding-top: 1%; direction: ltr;">
                <div class="container">
                    <div class="row">
                        <div class="COLR" style="float: right; direction: rtl">
                            <div class="table-responsive">
                                <table class="table table-striped" cellpadding="3" border="0" style="width: 97%; float: right; margin-right: 3%; max-width: 100%; margin-bottom: 20px;">
                                    <tr style="background-color: #2f323a;">
                                        <td style="width: 98px">
                                            <asp:Label ID="Label2" runat="server" Text="الشجرة المحاسبية" ForeColor="#f2f2f2" Font-Bold="True" Font-Size="Larger"></asp:Label>
                                        </td>
                                        <td class="auto-style1"></td>
                                    </tr>
                                    <tr>
                                        <td style="width: 98px">
                                            <asp:Label runat="server" Text="اسم الحساب / الفرع"></asp:Label>
                                        </td>
                                        <td class="auto-style1">
                                            <asp:TextBox AutoCompleteType="Disabled" runat="server" ID="Txt_AddFileName"></asp:TextBox>
                                        </td>

                                    </tr>
                                     <tr>
                                        <td style="width: 98px">
                                            <asp:Label runat="server" Text="حساب رئيسي/ مستوى اول"></asp:Label>
                                        </td>
                                        <td class="auto-style1">
                                            <asp:CheckBox ID="Ch_MainAccount" runat="server" />
                                        </td>

                                    </tr>
                                    <tr>
                                        <td>
                                            <asp:Button ID="Btn_Save" runat="server" Text="إدخال" OnClick="Btn_Save_Click" Height="26px" />
                                        </td>
                                        <td>
                                              <asp:Button ID="Btn_Delete" runat="server" Text="حذف" OnClick="Btn_Delete_Click" Height="26px" />
                                            <%--<a ID="Btn_Delete" onclick="return confirm('Are you sure you want to delete this item?');">حذف</a>--%>

                                            &nbsp; 	&nbsp; &nbsp; 
                                            <asp:Button ID="Btn_Update" runat="server" Text="تعديل" OnClick="Btn_Update_Click" Height="26px" />
                                       

                                        </td>
                                    </tr>
                                </table>


                            </div>
                        </div>


                        <div class="COLR" style="float: right; height:750px" >
                            <div class="table-responsive">
                                <table class="table-responsive">
                                    <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" dir="rtl" ImageSet="BulletedList2" NodeIndent="15" Style="text-align: center; font-size: medium" ExpandDepth="30" ShowLines="True" LineImagesFolder="~/TreeLineImages" NodeWrap="True" OnSelectedNodeChanged="TreeView1_SelectedNodeChanged">
                                <HoverNodeStyle Font-Underline="True" ForeColor="#6666AA" Font-Bold="True" Font-Size="XX-Large" Font-Strikeout="False" />
                                <LeafNodeStyle ImageUrl="~/img/document.png" />
                                <NodeStyle Font-Names="Sakkal Majalla" Font-Size="8pt" ForeColor="Black" HorizontalPadding="2px" NodeSpacing="0px" VerticalPadding="2px" />
                                <ParentNodeStyle Font-Bold="False" Font-Size="Medium" ImageUrl="~/img/folder-horizontal.png" />
                                <RootNodeStyle Font-Size="Medium" ImageUrl="~/img/folder-horizontal.png" />
                                <SelectedNodeStyle BackColor="#B5B5B5" Font-Underline="False" HorizontalPadding="0px" VerticalPadding="0px" />
                            </asp:TreeView>
                                </table>
                                <br />

                            </div>
                        </div>


                    </div>
                </div>
            </section>

</asp:Content>
